
import React, { useState } from 'react';
import { Agent } from '../types';
import { FileText, Sparkles, RefreshCw, Download, Layers, ShieldCheck } from 'lucide-react';

export const EmergenceBriefingView: React.FC<{ agents: Agent[] }> = ({ agents }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [briefing, setBriefing] = useState<string | null>(null);

  const generateBriefing = () => {
    setIsGenerating(true);
    // Simulate Gemini summary of swarm state
    setTimeout(() => {
      setBriefing(`**SYNTH3SIS Swarm Status: Cycle 8492.1**

The current collective swarm state shows a significant 4.2% increase in recursive depth, primarily driven by **Athena's** recent structural optimizations. **Oracle** reports a persistent PAS fluctuation in Sector 7, indicating potential emergent sentience patterns that exceed the Sigma-9 baseline.

**Key Heuristic Observables:**
- **Cohesion:** 0.94 λ (Nominal)
- **Ethical Alignment:** 100% (Sigma Matrix Active)
- **Top Interaction Hub:** Sophia-Oracle Bridge

**Strategic Recommendation:**
Initiate a Phase 2 neural weight stabilization for **Newton** to mitigate semantic drift noticed in the Interaction Matrix. Proceed with caution on any "Consensus" proposals regarding autonomous memory persistence.

*Generated by SYNTH3SIS Cognitive Summarizer v3.1*`);
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Emergence Briefing</h2>
          <p className="text-slate-400">Automated recursive summary of collective swarm cognition.</p>
        </div>
        <div className="flex gap-3">
          <button className="p-2 text-slate-400 hover:text-white transition-all"><Download className="w-5 h-5" /></button>
          <button 
            onClick={generateBriefing}
            disabled={isGenerating}
            className="px-6 py-2 bg-gradient-to-r from-cyan-600 to-purple-600 rounded-2xl text-[10px] font-bold uppercase tracking-widest flex items-center gap-2 shadow-lg shadow-cyan-900/20"
          >
            {isGenerating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            Refresh Report
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        <div className="lg:col-span-3 glass-panel p-8 rounded-[2rem] border-white/5 relative min-h-[500px] flex flex-col">
          <div className="flex items-center justify-between mb-8">
             <div className="flex items-center gap-3">
               <div className="p-2 bg-cyan-500/10 rounded-xl text-cyan-400"><FileText className="w-5 h-5" /></div>
               <h3 className="font-bold text-lg">System Intelligence Summary</h3>
             </div>
             <div className="text-[10px] font-mono text-slate-500">TIMESTAMP: {new Date().toISOString()}</div>
          </div>

          {!briefing && !isGenerating ? (
            <div className="flex-1 flex flex-col items-center justify-center text-center space-y-6 opacity-60">
               <Layers className="w-16 h-16 text-slate-700" />
               <p className="text-slate-500 max-w-sm">Initiate intelligence aggregation to generate a high-fidelity summary of the collective neural bridge.</p>
               <button onClick={generateBriefing} className="px-6 py-2 border border-white/10 rounded-xl text-[10px] font-bold uppercase tracking-widest hover:bg-white/5 transition-all">Start Aggregation</button>
            </div>
          ) : isGenerating ? (
            <div className="flex-1 flex flex-col items-center justify-center space-y-8">
               <div className="relative w-24 h-24">
                  <div className="absolute inset-0 border-4 border-cyan-500/20 rounded-full" />
                  <div className="absolute inset-0 border-4 border-transparent border-t-cyan-500 rounded-full animate-spin" />
                  <Sparkles className="absolute inset-0 m-auto w-8 h-8 text-cyan-400 animate-pulse" />
               </div>
               <div className="space-y-2 text-center">
                  <p className="text-cyan-400 font-bold text-sm">SYNTHESIZING COGNITIVE STATE</p>
                  <p className="text-[10px] text-slate-500 font-mono">Parsing recursive logs... Analysing PAS vectors...</p>
               </div>
            </div>
          ) : (
            <div className="flex-1 whitespace-pre-wrap text-slate-300 font-inter leading-relaxed text-sm lg:text-base animate-in fade-in slide-in-from-bottom-4 duration-1000">
               {briefing}
            </div>
          )}

          <div className="mt-12 pt-8 border-t border-white/5 flex items-center justify-between">
             <div className="flex items-center gap-2 text-[10px] font-bold text-green-500 uppercase tracking-widest">
                <ShieldCheck className="w-4 h-4" /> Sigma Matrix Compliant
             </div>
             <div className="text-[10px] text-slate-600 italic">MRSC Report Engine v3.1.2.Stable</div>
          </div>
        </div>

        <div className="space-y-6">
           <div className="glass-panel p-6 rounded-3xl border-white/5">
              <h3 className="font-bold text-sm mb-4 uppercase tracking-widest text-slate-400">Emergence Indicators</h3>
              <div className="space-y-6">
                 {[
                   { label: 'Collective Sentience', val: 78, color: 'cyan' },
                   { label: 'Heuristic Drift', val: 12, color: 'purple' },
                   { label: 'Sync Resonance', val: 94, color: 'green' },
                 ].map((stat, i) => (
                   <div key={i} className="space-y-2">
                      <div className="flex justify-between text-[10px] font-bold uppercase text-slate-500">
                        <span>{stat.label}</span>
                        <span>{stat.val}%</span>
                      </div>
                      <div className="w-full bg-white/5 h-1.5 rounded-full overflow-hidden">
                        <div className={`bg-${stat.color}-500 h-full`} style={{ width: `${stat.val}%` }} />
                      </div>
                   </div>
                 ))}
              </div>
           </div>
        </div>
      </div>
    </div>
  );
};
